version: "3.6"

services:
  nginx:
    build: .
    environment: 
      CT_LOCAL_CONFIG: >-
        consul {
          address = "vault_consul_1:8500"
          retry {
            enabled = true
            attempts = 12
            backoff = "250ms"

          }
        }
        reload_signal = "SIGHUP"
        kill_signal = "SIGINT"
        max_stale = "10m"
        log_level = "warn"
        pid_file = "/consul-template/consul-template.pid"
        wait {
          min = "5s"
          max = "10s"
        }

        vault {
          address = "http://vault_vault_1:8200"
          # This value can also be specified via the environment variable VAULT_TOKEN.
          token = "9b02e1d9-31da-bb4b-4c48-62220b163da7"
          renew_token = false
        }

        deduplicate {
          enabled = true
          prefix = "consul-template/dedup/"
        }


        template {
          source = "./nginx/templates/upstream.conf.ctmpl"
          destination = "/etc/nginx/conf.d/upstream.conf"
          command = "nginx reload"
          command_timeout = "60s"
          perms = 0600
          backup = true
          left_delimiter  = "{{"
          right_delimiter = "}}"
          wait {
            min = "2s"
            max = "10s"
          }
        }

        template {
          source = "./nginx/templates/server.conf.ctmpl"
          destination = "/etc/nginx/conf.d/server.conf"
          command = "nginx reload"
          command_timeout = "60s"
          perms = 0600
          backup = true
          left_delimiter  = "{{"
          right_delimiter = "}}"
          wait {
            min = "2s"
            max = "10s"
          }
        }
    ports:
      - 9090:80
    volumes:
      - ${PWD}/nginx/config.hcl:/consul-template/config.d/config.hcl
      - ${PWD}/nginx/templates:/consul-template/templates/
    command: /usr/local/bin/consul-template